### ISSUE TITLE
Can't export full collection

### ISSUE THREAD

**Issue by jabalong** [matt-h/rdio-enhancer#47]
Hello,  the "Export to CSV" option has stopped working for me again of late.

Have been trying it for a week with no luck. Last time I successfully used it was 8 Feb.

Am getting this error:

“There was an error getting the Favorites data, if you have a large amount of favorites try scrolling down to load more first and then try the action again.”

First time I've seen this error (using extension since last Jun).

Tried scrolling through list to no avail.

Have about 5,000 favorites (large amount?), but this number hasn't changed much in a while, so don't know why it would suddenly be a problem.

Am using latest version of rdio-enhancer (2.8.3) and Chrome (40.0.2214.115).

Any thoughts?

**Comment by matt-h** [comment]
I just tested it with my account and it works fine.
It could be the large amount, I have about 2000 in mine which worked.

Can you check the console in Chrome and see if it gives you any error messages when you do the export? That will help with tracking down the issue.

**Comment by jabalong** [comment]
Ugh, was afraid it could just be me! :P

I'm not familiar with the Console, but I poked around the Developer tools and seem to have found it.

Am pasting below what's there from this morning (after opening Chrome, going to rdio.com, then Favorites, letting it load until URL pop-up in lower-left corner disappears, hitting Export to CSV, then getting error message). Apologies if this is too long.
________________________

chrome-extension://boadgeojelhgndaghljhdicfkmllpafd/cast_sender.js Failed to load resource: net::ERR_FAILED
VM62:27 loading.target.rdio: 82.132ms
chrome-extension://dliochdbjfkdbacpmhlcpmleaejidimm/cast_sender.js Failed to load resource: net::ERR_FAILED
chrome-extension://hfaagokkkhdbgiakmmlclaapfelnkoah/cast_sender.js Failed to load resource: net::ERR_FAILED
chrome-extension://fmfcbgogabcbclcofgocippekhfcmgfj/cast_sender.js Failed to load resource: net::ERR_FAILED
chrome-extension://enhhojjnijigcajfphajepfemndkmdlo/cast_sender.js Failed to load resource: net::ERR_FAILED
VM62:75 No cast extension found
VM62:27 loading.js: 1307.066ms
logger.fb10ab2262be664b45dfec5093553f32.js:41 [Sun Mar 01 2015 09:11:39 GMT+0800 (China Standard Time)] [AudioFactory] Player with native audio true has priority 2: default preference
logger.fb10ab2262be664b45dfec5093553f32.js:41 [Sun Mar 01 2015 09:11:39 GMT+0800 (China Standard Time)] [AudioFactory] Player with native audio false has priority 1: default preference
logger.fb10ab2262be664b45dfec5093553f32.js:41 [Sun Mar 01 2015 09:11:39 GMT+0800 (China Standard Time)] [Services] Loader is ready
logger.fb10ab2262be664b45dfec5093553f32.js:41 [Sun Mar 01 2015 09:11:39 GMT+0800 (China Standard Time)] [Services] Storage is ready
logger.fb10ab2262be664b45dfec5093553f32.js:41 [Sun Mar 01 2015 09:11:39 GMT+0800 (China Standard Time)] [Services] ShortcutManager is ready
logger.fb10ab2262be664b45dfec5093553f32.js:41 [Sun Mar 01 2015 09:11:39 GMT+0800 (China Standard Time)] [Services] WebSocketFactory is ready
logger.fb10ab2262be664b45dfec5093553f32.js:41 [Sun Mar 01 2015 09:11:39 GMT+0800 (China Standard Time)] [Services] Notifications is ready
logger.fb10ab2262be664b45dfec5093553f32.js:41 [Sun Mar 01 2015 09:11:39 GMT+0800 (China Standard Time)] [Services] OfflineMonitor is ready
logger.fb10ab2262be664b45dfec5093553f32.js:41 [Sun Mar 01 2015 09:11:39 GMT+0800 (China Standard Time)] [Timer] loading.target.rdio: 82
logger.fb10ab2262be664b45dfec5093553f32.js:41 [Sun Mar 01 2015 09:11:39 GMT+0800 (China Standard Time)] [Timer] loading.js: 1307
logger.fb10ab2262be664b45dfec5093553f32.js:41 [Sun Mar 01 2015 09:11:39 GMT+0800 (China Standard Time)] [Services] Stats is ready
logger.fb10ab2262be664b45dfec5093553f32.js:41 [Sun Mar 01 2015 09:11:39 GMT+0800 (China Standard Time)] [Services] Instrumentation is ready
logger.fb10ab2262be664b45dfec5093553f32.js:41 [Sun Mar 01 2015 09:11:39 GMT+0800 (China Standard Time)] [Services] ErrorReporter is ready
logger.fb10ab2262be664b45dfec5093553f32.js:41 [Sun Mar 01 2015 09:11:39 GMT+0800 (China Standard Time)] [Services] EventReporter is ready
logger.fb10ab2262be664b45dfec5093553f32.js:41 [Sun Mar 01 2015 09:11:39 GMT+0800 (China Standard Time)] [Services] Defer is ready
logger.fb10ab2262be664b45dfec5093553f32.js:41 [Sun Mar 01 2015 09:11:39 GMT+0800 (China Standard Time)] [Services] Hive is ready
logger.fb10ab2262be664b45dfec5093553f32.js:41 [Sun Mar 01 2015 09:11:39 GMT+0800 (China Standard Time)] [FallbackWrapper] Embedding fallback swf
logger.fb10ab2262be664b45dfec5093553f32.js:41 [Sun Mar 01 2015 09:11:39 GMT+0800 (China Standard Time)] [Services] AutoPlay is ready
logger.fb10ab2262be664b45dfec5093553f32.js:41 [Sun Mar 01 2015 09:11:39 GMT+0800 (China Standard Time)] [Services] Omniture is ready
logger.fb10ab2262be664b45dfec5093553f32.js:41 [Sun Mar 01 2015 09:11:39 GMT+0800 (China Standard Time)] [Services] ContinuousBenchmarks is ready
logger.fb10ab2262be664b45dfec5093553f32.js:41 [Sun Mar 01 2015 09:11:39 GMT+0800 (China Standard Time)] [Services] LayoutManager is ready
logger.fb10ab2262be664b45dfec5093553f32.js:41 [Sun Mar 01 2015 09:11:39 GMT+0800 (China Standard Time)] [Services] Updater is ready
stats.fb10ab2262be664b45dfec5093553f32.js:260 swf_embed: 155.457ms
logger.fb10ab2262be664b45dfec5093553f32.js:41 [Sun Mar 01 2015 09:11:39 GMT+0800 (China Standard Time)] [Services] FallbackWrapper is ready
logger.fb10ab2262be664b45dfec5093553f32.js:41 [Sun Mar 01 2015 09:11:39 GMT+0800 (China Standard Time)] [Services] AudioFactory is ready
logger.fb10ab2262be664b45dfec5093553f32.js:41 [Sun Mar 01 2015 09:11:39 GMT+0800 (China Standard Time)] [Services] Facebook is ready
logger.fb10ab2262be664b45dfec5093553f32.js:41 [Sun Mar 01 2015 09:11:39 GMT+0800 (China Standard Time)] [PubSub] connecting...
logger.fb10ab2262be664b45dfec5093553f32.js:41 [Sun Mar 01 2015 09:11:39 GMT+0800 (China Standard Time)] [PlayerData] using local playerstate because it's the same version
logger.fb10ab2262be664b45dfec5093553f32.js:41 [Sun Mar 01 2015 09:11:39 GMT+0800 (China Standard Time)] [Player] [EventReporter] Clearing old transaction: undefined
logger.fb10ab2262be664b45dfec5093553f32.js:41 [Sun Mar 01 2015 09:11:39 GMT+0800 (China Standard Time)] [Services] Player is ready
logger.fb10ab2262be664b45dfec5093553f32.js:41 [Sun Mar 01 2015 09:11:40 GMT+0800 (China Standard Time)] [Services] ABTest is ready
logger.fb10ab2262be664b45dfec5093553f32.js:41 [Sun Mar 01 2015 09:11:40 GMT+0800 (China Standard Time)] [Analytics] : loaded | s22068638 | jabalong
logger.fb10ab2262be664b45dfec5093553f32.js:41 [Sun Mar 01 2015 09:11:40 GMT+0800 (China Standard Time)] [Services] Analytics is ready
logger.fb10ab2262be664b45dfec5093553f32.js:41 [Sun Mar 01 2015 09:11:40 GMT+0800 (China Standard Time)] [Analytics] : page | undefined | jabalong
logger.fb10ab2262be664b45dfec5093553f32.js:41 [Sun Mar 01 2015 09:11:40 GMT+0800 (China Standard Time)] [Analytics] : identify | s22068638 | jabalong
logger.fb10ab2262be664b45dfec5093553f32.js:41 [Sun Mar 01 2015 09:11:40 GMT+0800 (China Standard Time)] [WebSocketFactory] Natively trying to connect to:  pubsub2.rdio.com:8081
https://r.turn.com/r/beacon?b2=lntBqc7W7-3_V84avb4yUR-A8FJGgUqKy6JxNQ4aKAy8Rt4jv52uiyiUJErl7AiHTb6lF0B4DwM_C7J3J3YjVQ&cid=&gtmcb=657907578 Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
logger.fb10ab2262be664b45dfec5093553f32.js:41 [Sun Mar 01 2015 09:11:41 GMT+0800 (China Standard Time)] Backbone.Collection#set is now the default updating mechanism after a fetch.
If you would like to use "reset", pass `{ reset: true }`.
logger.fb10ab2262be664b45dfec5093553f32.js:41 [Sun Mar 01 2015 09:11:41 GMT+0800 (China Standard Time)] using component: MusicFeed
stats.fb10ab2262be664b45dfec5093553f32.js:260 appLoad_App_Rdio: 2457.342ms
logger.fb10ab2262be664b45dfec5093553f32.js:41 [Sun Mar 01 2015 09:11:41 GMT+0800 (China Standard Time)] [WebSocketFactory] Native websocket opened.
logger.fb10ab2262be664b45dfec5093553f32.js:41 [Sun Mar 01 2015 09:11:41 GMT+0800 (China Standard Time)] [PubSub] Subscribing to: s22068638/fields s22068638/playlists
logger.fb10ab2262be664b45dfec5093553f32.js:41 [Sun Mar 01 2015 09:11:41 GMT+0800 (China Standard Time)] [Services] PubSub is ready
logger.fb10ab2262be664b45dfec5093553f32.js:41 [Sun Mar 01 2015 09:11:41 GMT+0800 (China Standard Time)] [PubSub] Subscribing to: s22068638/private
logger.fb10ab2262be664b45dfec5093553f32.js:41 [Sun Mar 01 2015 09:11:41 GMT+0800 (China Standard Time)] [PubSub] Subscribing to: s22068638/presence
logger.fb10ab2262be664b45dfec5093553f32.js:41 [Sun Mar 01 2015 09:11:41 GMT+0800 (China Standard Time)] [PubSub] Subscribing to: s22068638/player
logger.fb10ab2262be664b45dfec5093553f32.js:41 [Sun Mar 01 2015 09:11:41 GMT+0800 (China Standard Time)] [PubSub] Publishing message: PUB s22068638/player|{"event":"masterQuery"}
logger.fb10ab2262be664b45dfec5093553f32.js:41 [Sun Mar 01 2015 09:11:42 GMT+0800 (China Standard Time)] [PubSub] Received message:  s22068638/presence {"event":"connectionJoin","user":"s22068638","id":"ec90c490-bfaf-11e4-8073-d3cf71e446bd","caps":{"player":{"canRemote":true,"name":"_web_5121142"}}} Sun Mar 01 2015 09:11:42 GMT+0800 (China Standard Time)
logger.fb10ab2262be664b45dfec5093553f32.js:41 [Sun Mar 01 2015 09:11:42 GMT+0800 (China Standard Time)] [PubSub] Received message:  s22068638/presence {"event":"join","user":"s22068638"} Sun Mar 01 2015 09:11:42 GMT+0800 (China Standard Time)
logger.fb10ab2262be664b45dfec5093553f32.js:41 [Sun Mar 01 2015 09:11:42 GMT+0800 (China Standard Time)] [PubSub] Received message:  s22068638/presence {"event":"connectionJoin","user":"s22068638","id":"ec90c490-bfaf-11e4-8073-d3cf71e446bd","caps":{"player":{"canRemote":true,"name":"_web_5121142"}}} Sun Mar 01 2015 09:11:42 GMT+0800 (China Standard Time)
2logger.fb10ab2262be664b45dfec5093553f32.js:41 [Sun Mar 01 2015 09:11:42 GMT+0800 (China Standard Time)] [Analytics] : identify | s22068638 | jabalong
stats.fb10ab2262be664b45dfec5093553f32.js:260 renderPage.MusicFeed: 795.652ms
logger.fb10ab2262be664b45dfec5093553f32.js:41 [Sun Mar 01 2015 09:11:43 GMT+0800 (China Standard Time)] [Omniture] : t() data sent
logger.fb10ab2262be664b45dfec5093553f32.js:41 [Sun Mar 01 2015 09:11:43 GMT+0800 (China Standard Time)] API call failed: {"cursor":null,"count":5,"extras":"[{\"field\":\"*.WEB\"},{\"field\":\"bigIcon\",\"extras\":[\"*.WEB\",\"*.WEB\"]},{\"field\":\"commenter\",\"extras\":[\"*.WEB\",\"*.WEB\"]},{\"field\":\"commentedItem\",\"extras\":[\"*.WEB\",\"*.WEB\",\"album\"]},{\"field\":\"SimpleComment.url\",\"extras\":[\"*.WEB\",\"*.WEB\"]},{\"field\":\"SimpleComment.likes\",\"start\":0,\"count\":0,\"extras\":[\"*.WEB\",\"*.WEB\"]},{\"field\":\"SimpleComment.liked\",\"extras\":[\"*.WEB\",\"*.WEB\"]},{\"field\":\"SimpleComment.replyCount\",\"extras\":[\"*.WEB\",\"*.WEB\"]},{\"field\":\"tracks\",\"exclude\":true},{\"field\":\"count\",\"exclude\":true},{\"field\":\"length\",\"exclude\":true},{\"field\":\"artists\",\"extras\":[\"*.WEB\",\"*.WEB\",\"-*\",\"name\",\"url\"]},{\"field\":\"Album.length\",\"extras\":[\"*.WEB\",\"*.WEB\"]},{\"field\":\"Album.iconKey\",\"extras\":[\"*.WEB\",\"*.WEB\"]},{\"field\":\"Album.artistAvatarIcon\",\"extras\":[\"*.WEB\",\"*.WEB\"]},{\"field\":\"Artist.albumCount\",\"extras\":[\"*.WEB\",\"*.WEB\"]},{\"field\":\"Artist.avatarIcon\",\"extras\":[\"*.WEB\",\"*.WEB\"]},{\"field\":\"Artist.length\",\"extras\":[\"*.WEB\",\"*.WEB\"]},{\"field\":\"Track.iconKey\",\"extras\":[\"*.WEB\",\"*.WEB\"]},{\"field\":\"Playlist.iconKeys\",\"extras\":[\"*.WEB\",\"*.WEB\"]},{\"field\":\"Playlist.isViewable\",\"extras\":[\"*.WEB\",\"*.WEB\"]},{\"field\":\"Playlist.canCollaborate\",\"extras\":[\"*.WEB\",\"*.WEB\"]},{\"field\":\"description\",\"extras\":[\"*.WEB\",\"*.WEB\"]},{\"field\":\"influencerName\",\"extras\":[\"*.WEB\",\"*.WEB\"]},{\"field\":\"lastSourcePlayed\",\"extras\":[\"*.WEB\",\"*.WEB\"]},{\"field\":\"lastSongPlayed\",\"extras\":[\"*.WEB\",\"*.WEB\"]},{\"field\":\"suggestionSource\",\"extras\":[\"*.WEB\",\"*.WEB\"]},{\"field\":\"displayedUser\",\"extras\":[\"*.WEB\",\"*.WEB\",\"-*\",\"key\",\"type\",\"url\",\"icon\",\"firstName\",\"lastName\",\"canUnfollow\"]},{\"field\":\"Playlist.hasCustomArtwork\",\"extras\":[\"*.WEB\",\"*.WEB\"]},{\"field\":\"EditorialCollectionItem.content\",\"extras\":[{\"field\":\"*.WEB\"},{\"field\":\"*.WEB\"},{\"field\":\"artists\",\"extras\":[\"*.WEB\",\"*.WEB\",\"-*\",\"name\",\"url\"]},{\"field\":\"iconKeys\",\"extras\":[\"*.WEB\",\"*.WEB\"]}]}]","cardSpecificExtras":"{\"popular_network\":[\"Album.networkConsumersWithCounts\"],\"keep_listening\":[\"ArtistStation.iconKeys\",\"ArtistTopSongsStation.iconKeys\",\"UserCollectionStation.iconKeys\",\"HeavyRotationStation.iconKeys\",\"HeavyRotationUserStation.iconKeys\",\"LabelStation.iconKeys\",\"SongStation.iconKeys\",\"TasteProfileStation.iconKeys\",\"UserCollectionStation.iconKeys\",\"GenreStation.iconKeys\",\"PlaylistStation.iconKeys\",\"AlbumStation.iconKeys\"]}","artistSeeds":[],"method":"getMusicFeed","_authorization_key":"eyJyYW5kIjogMTgxNzM5NjgwOSwgImtleSI6ICJzMjIwNjg2MzgiLCAidGltZSI6IDE0MjUxNzIyOTl9.Uc1e4byZOJznbk9W8SFW3c19PCk","v":20141119}
http://ib.adnxs.com/px?id=85439&seg=813277&t=1 Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
http://bs.serving-sys.com/BurstingPipe/ActivityServer.bs?cn=as&amp;ActivityID=378293&amp;ns=1 Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
http://bs.serving-sys.com/Serving/ActivityServer.bs?cn=as&amp;ActivityID=531653&amp;ns=1 Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
logger.fb10ab2262be664b45dfec5093553f32.js:41 [Sun Mar 01 2015 09:11:43 GMT+0800 (China Standard Time)] [Analytics] : App Launched | jabalong | jabalong
logger.fb10ab2262be664b45dfec5093553f32.js:41 [Sun Mar 01 2015 09:11:46 GMT+0800 (China Standard Time)] [PubSub] Subscribing to: s26737790/presence
logger.fb10ab2262be664b45dfec5093553f32.js:41 [Sun Mar 01 2015 09:11:46 GMT+0800 (China Standard Time)] [PubSub] Subscribing to: s15065043/presence
logger.fb10ab2262be664b45dfec5093553f32.js:41 [Sun Mar 01 2015 09:11:46 GMT+0800 (China Standard Time)] [PubSub] Subscribing to: s3991332/presence
logger.fb10ab2262be664b45dfec5093553f32.js:41 [Sun Mar 01 2015 09:11:46 GMT+0800 (China Standard Time)] [PubSub] Subscribing to: s26452978/presence
logger.fb10ab2262be664b45dfec5093553f32.js:41 [Sun Mar 01 2015 09:11:46 GMT+0800 (China Standard Time)] [PubSub] Subscribing to: s2158503/presence
logger.fb10ab2262be664b45dfec5093553f32.js:41 [Sun Mar 01 2015 09:11:46 GMT+0800 (China Standard Time)] [PubSub] Subscribing to: s30240293/presence
logger.fb10ab2262be664b45dfec5093553f32.js:41 [Sun Mar 01 2015 09:11:47 GMT+0800 (China Standard Time)] [Analytics] : Important Nav Item Clicked | jabalong | jabalong
logger.fb10ab2262be664b45dfec5093553f32.js:41 [Sun Mar 01 2015 09:11:47 GMT+0800 (China Standard Time)] using component: Profile.Favorites
stats.fb10ab2262be664b45dfec5093553f32.js:260 renderPage.Profile_Favorites: 29.594ms
logger.fb10ab2262be664b45dfec5093553f32.js:41 [Sun Mar 01 2015 09:11:47 GMT+0800 (China Standard Time)] [Omniture] : t() data sent
http://ib.adnxs.com/px?id=85439&seg=813277&t=1 Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
http://bs.serving-sys.com/BurstingPipe/ActivityServer.bs?cn=as&amp;ActivityID=378293&amp;ns=1 Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
http://bs.serving-sys.com/Serving/ActivityServer.bs?cn=as&amp;ActivityID=531653&amp;ns=1 Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
logger.fb10ab2262be664b45dfec5093553f32.js:41 [Sun Mar 01 2015 09:12:31 GMT+0800 (China Standard Time)] Error in API call: Object Object
logger.fb10ab2262be664b45dfec5093553f32.js:41 [Sun Mar 01 2015 09:12:31 GMT+0800 (China Standard Time)] API call failed: {"extras":["*.WEB"],"method":"getTracksInCollection","_authorization_key":"eyJyYW5kIjogMTgxNzM5NjgwOSwgImtleSI6ICJzMjIwNjg2MzgiLCAidGltZSI6IDE0MjUxNzIyOTl9.Uc1e4byZOJznbk9W8SFW3c19PCk","v":20141119}

**Comment by matt-h** [comment]
Thanks for the logs, I updated it to just the relevant lines of the error just in case there was any private information in there about your account.

It does say that the API call to getTracksInCollection is failing, but gives no details.

Also in Developer Tools can you go to the Network tab and then try the export again. On the left side find the request for getTracksInCollection and on the right side copy the Response Headers under the Headers tab and everything under the Response tab. Hopefully that will tell us what the error is.

![rdioissue](https://cloud.githubusercontent.com/assets/664294/6429229/6f913550-bf92-11e4-99cc-74da4b458f30.png)

**Comment by jabalong** [comment]
Okay, there were a few instances of "getTracksInCollection" as I had tried "Export to CSV" a few times and it seems to create a new instance each time. Here is the info from one of them under "Response Headers":

Access-Control-Allow-Origin:*
Cache-Control:no-cache
Connection:keep-alive
Content-Language:en
Content-Length:55
Content-Type:application/json
Date:Sun, 01 Mar 2015 03:35:27 GMT
Server:nginx/1.2.4
Vary:Accept-Language, Cookie
X-Client-Version:7a717bfd5d7ae5aa38fb2ba82cec5caced82ac5e
X-NewRelic-App-Data:PxQFU1dQAAUTVVdWDgcEX0YdFGQHBDcQUQxLA1tMXV1dSmsFWA4cAxRfGBdXTF9WRDATA1RaRC8KcllfDgMAFlkNVkAUCBgBHVAMUgNQAVpcBwdZXlENBBxVWVcbE1FfXAJUB1RVVANTUAoBXVoWHlUEVRJUPA==
X-srv:srv-107-09
X-Version:720

**Comment by matt-h** [comment]
Looks like the server is just doing a generic Internal Server Error for the call which isn't very useful for us. It should send the list of all tracks if is working. 
My guess it is because it is trying to send so many at once. I'll look into implementing the limit and break it up into multiple calls if getting too many tracks.

**Comment by jabalong** [comment]
Just tried it again today and it worked! Thanks!
