### ISSUE TITLE
Export full collection to csv

### ISSUE THREAD

**Issue by kwancho** [matt-h/rdio-enhancer#50]
I have a pretty large collection, and when I click on the export to CSV, I get the "Fetching Favorites data... Please wait.  If your Favorites is large this can take a while" popup, but then it goes away after about 10 seconds with no further actions.

Console error:
![screen shot 2015-07-07 at 9 29 24 am](https://cloud.githubusercontent.com/assets/13223126/8551340/c4894950-248a-11e5-9609-b842cde19356.jpg)

**Comment by matt-h** [comment]
Thanks for the report. The popup does disappear after about 10 seconds even if it isn't done (maybe I should add more if it is extra large).

That console error is unrelated to the export, so that shouldn't be the issue.

If you go to the Network tab in the Developer Tools it should be making multiple calls to "getTracksInCollection". If those continue without error then it is still building the CSV.

**Comment by kwancho** [comment]
Ah, cool.  It is still making those calls.  Guess I'm just impatient!

**Comment by matt-h** [comment]
You must have a large collection then. I'm curious how many tracks it ends up with and if it completes successfully.
The largest I've tested with so far is around 5000 tracks.

**Comment by kwancho** [comment]
I let it run three times, and each time Chrome crashes out before it finishes

![screen shot 2015-07-07 at 10 27 38 am](https://cloud.githubusercontent.com/assets/13223126/8552683/79192bf8-2493-11e5-9121-089cd4214ca0.jpg)

**Comment by matt-h** [comment]
That is a lot of tracks in your library, that is 20000 tracks worth of requests on the screen there.

Chrome is running out of memory and crashing before it can get everthing.

**Comment by matt-h** [comment]
I just uploaded version 2.8.5 which might fix this issue by breaking the download into multiple CSV files with 15000 tracks in each. When it is available to you please update to the new version and see if that fixes Chrome crashing on you.

**Comment by kwancho** [comment]
So, it finishes collection and collection(1), which are each exactly 15,000
songs (up to T for me), but then for the third, the getTracks starts taking
~130ms instead of 6-8s and it doesn't end up completing.  So close!  Thanks
for the updates so far....

[image: Inline image 1]

**Comment by kwancho** [comment]
![screen shot 2015-07-07 at 3 22 53 pm](https://cloud.githubusercontent.com/assets/13223126/8558872/643d30c0-24bc-11e5-8cfb-54a9032640dc.jpg)
