### ISSUE TITLE
Add all songs from an artist to a playlist

### ISSUE THREAD

**Issue by DemosMirak** [matt-h/rdio-enhancer#60]
Hello,

I would like to request a feature to add all songs from an artist to a playlist of choice.
This is because not all the songs from the artist are listed in his or her albums, but rather in the albums published by their labels. As it stands now, I would have to add all the songs by hand, which is a pain.
Should this already be a feature, I am then sorry for bothering you.
Many thanks for the add-on.

**Comment by ryan-nauman** [comment]
Can you link some examples?

**Comment by DemosMirak** [comment]
For some reason I can't connect to rdio at the moment, keep getting connection reset error, but of the top of my head there is Feint. He got 51 songs on rdio, but only 19 are in albums of his. And I'm guessing that artists working with the same label as he is, Monstercat, have the same problem. I will add more once I get my connection back/

**Comment by ryan-nauman** [comment]
I would use this. I will implement it next

**Comment by DemosMirak** [comment]
Thanks!

**Comment by ryan-nauman** [comment]
See #62 for the proposed change
