### ISSUE TITLE
Favorite collections larger than 30000 songs?

### ISSUE THREAD

**Issue by scottiejibbs** [matt-h/rdio-enhancer#66]
First - thank you so much for this extension.  I'm one of the long time rdio users scrambling to export their collection :)  I notice the update to handle collections over 15k.  In my case, it appears my collection exceeds 30k songs.  I see the notification, roughly "large collection, will export multiple csv files", but it seems to stop after exporting two 15k song csv files.  Is this a known limitation of the extension, or of the api?  Should it in theory work for collections over 30k?   Thanks so much!!

**Comment by edsu** [comment]
Mine seems to cap out at 15k. I would really appreciate being able to increase this if it's easy.

**Comment by matt-h** [comment]
I fixed a bug here that was causing it to stop after 2 csv files.

I also added an input box so you can put the number to start on, such as `15000` or `30000` which will start a new export on that number in case something bugs out in the API from too many requests at once.

This will be up in version 2.10.1 which should be available as soon as it goes through publication by Google.

**Comment by scottiejibbs** [comment]
Matt -- you are awesome!!   Thank you so much for the update!!

**Comment by edsu** [comment]
Thanks!
