### ISSUE TITLE
Can't exports playlists

### ISSUE THREAD

**Issue by arliber** [matt-h/rdio-enhancer#69]
I have successfully exported my Favorites collection (which is huge) but non of my play lists are getting exported (even the tiny ones with 421 songs or so).

Please help :(

**Comment by Anzumana** [comment]
what browser are u using. I just did my entire collection and all my playlists. Using Chrome on Mac.
No issue at all.

**Comment by matt-h** [comment]
It works for me, so I'm not sure.

Maybe try refreshing the page just to make sure everything is loaded?

If you still arn't getting anything, can you check the browser's console to see if there are any errors?

**Comment by arliber** [comment]
Hi guys,
Thanks for reaching out!
I force-reloaded the page and it worked with no problems at all, should've done that before posting.
All backed up now, ready for Spotify :(
